# Kafka Incoming (Fraud Alerts)
mp.messaging.incoming.fraud-alerts-in.connector=smallrye-kafka
mp.messaging.incoming.fraud-alerts-in.topic=fraud-alerts
mp.messaging.incoming.fraud-alerts-in.value.deserializer=com.fraud.detection.notification.consumer.AlertDeserializer

# HTTP
quarkus.http.port=8083

# CORS (Allow WebSocket connections from Angular)
quarkus.http.cors=true
quarkus.http.cors.origins=*
