# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Kafka Configuration
mp.messaging.connector.smallrye-kafka.bootstrap.servers=kafka:9092

# Kafka Outgoing Channel
mp.messaging.outgoing.transactions-out.connector=smallrye-kafka
mp.messaging.outgoing.transactions-out.topic=transactions
mp.messaging.outgoing.transactions-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# HTTP
quarkus.http.port=8081
