# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}

# Hibernate
quarkus.hibernate-orm.database.generation=update

# Kafka Incoming (Transactions)
mp.messaging.incoming.transactions-in.connector=smallrye-kafka
mp.messaging.incoming.transactions-in.topic=transactions
mp.messaging.incoming.transactions-in.value.deserializer=com.fraud.detection.fraud.consumer.TransactionDeserializer

# Kafka Outgoing (Alerts)
mp.messaging.outgoing.fraud-alerts.connector=smallrye-kafka
mp.messaging.outgoing.fraud-alerts.topic=fraud-alerts
mp.messaging.outgoing.fraud-alerts.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# AI Configuration (Gemini)
quarkus.langchain4j.google-gemini.api-key=${GEMINI_API_KEY}
quarkus.langchain4j.google-gemini.model-name=gemini-1.5-flash

# HTTP
quarkus.http.port=8082
