# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}

# Hibernate
quarkus.hibernate-orm.database.generation=update

# Kafka Configuration
mp.messaging.connector.smallrye-kafka.bootstrap.servers=kafka:9092

# Kafka Incoming (Transactions)
mp.messaging.incoming.transactions-in.connector=smallrye-kafka
mp.messaging.incoming.transactions-in.topic=transactions
mp.messaging.incoming.transactions-in.value.deserializer=com.fraud.detection.fraud.consumer.TransactionDeserializer

mp.messaging.outgoing.fraud-alerts.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# AI Configuration (Gemini via OpenAI standard protocol)
quarkus.langchain4j.chat-model.provider=openai
quarkus.langchain4j.openai.api-key=${GEMINI_API_KEY}
quarkus.langchain4j.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/v1/
quarkus.langchain4j.openai.chat-model.model-name=gemini-1.5-flash
quarkus.langchain4j.openai.log-requests=true
quarkus.langchain4j.openai.log-responses=true

# HTTP
quarkus.http.port=8082
